In [63]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('default')

In [64]:
import ssl
ssl._create_default_https_context = ssl._create_unverified_context


In [65]:
df = sns.load_dataset("titanic")

In [66]:
import ssl
print(ssl.get_default_verify_paths())


DefaultVerifyPaths(cafile=None, capath=None, openssl_cafile_env='SSL_CERT_FILE', openssl_cafile='/Library/Frameworks/Python.framework/Versions/3.13/etc/openssl/cert.pem', openssl_capath_env='SSL_CERT_DIR', openssl_capath='/Library/Frameworks/Python.framework/Versions/3.13/etc/openssl/certs')


In [67]:
df = pd.read_csv('titanic.csv')
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [68]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [69]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   survived     891 non-null    int64  
 1   pclass       891 non-null    int64  
 2   sex          891 non-null    object 
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64  
 5   parch        891 non-null    int64  
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object 
 8   class        891 non-null    object 
 9   who          891 non-null    object 
 10  adult_male   891 non-null    bool   
 11  deck         203 non-null    object 
 12  embark_town  889 non-null    object 
 13  alive        891 non-null    object 
 14  alone        891 non-null    bool   
dtypes: bool(2), float64(2), int64(4), object(7)
memory usage: 92.4+ KB


In [70]:
df.drop(['deck', 'embark_town',
       'alive','class','who', 'adult_male'],axis=1,inplace=True)
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'alone'],
      dtype='object')

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  891 non-null    int64  
 1   pclass    891 non-null    int64  
 2   sex       891 non-null    object 
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64  
 5   parch     891 non-null    int64  
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object 
 8   alone     891 non-null    bool   
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 56.7+ KB


In [72]:
# df["age"].fillna(df['age'].mean(),inplace=True)
df['age'] = df['age'].mean()

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  891 non-null    int64  
 1   pclass    891 non-null    int64  
 2   sex       891 non-null    object 
 3   age       891 non-null    float64
 4   sibsp     891 non-null    int64  
 5   parch     891 non-null    int64  
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object 
 8   alone     891 non-null    bool   
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 56.7+ KB


In [74]:
df.dropna(subset=['embarked'],inplace=True) 

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  889 non-null    int64  
 1   pclass    889 non-null    int64  
 2   sex       889 non-null    object 
 3   age       889 non-null    float64
 4   sibsp     889 non-null    int64  
 5   parch     889 non-null    int64  
 6   fare      889 non-null    float64
 7   embarked  889 non-null    object 
 8   alone     889 non-null    bool   
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 63.4+ KB


In [76]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [77]:
df['sex'] = le.fit_transform(df['sex'])
df['embarked'] = le.fit_transform(df['embarked'])
df.astype(int)

survived  pclass  sex  age  sibsp  parch  fare  embarked  alone
0           0       3    1   29      1      0     7         2      0
1           1       1    0   29      1      0    71         0      0
2           1       3    0   29      0      0     7         2      1
3           1       1    0   29      1      0    53         2      0
4           0       3    1   29      0      0     8         2      1
..        ...     ...  ...  ...    ...    ...   ...       ...    ...
886         0       2    1   29      0      0    13         2      1
887         1       1    0   29      0      0    30         2      1
888         0       3    0   29      1      2    23         2      0
889         1       1    1   29      0      0    30         0      1
890         0       3    1   29      0      0     7         1      1

[889 rows x 9 columns]

In [78]:
X = df.drop('survived',axis=1)
y = df['survived']

In [79]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

model.fit(X_train,y_train)

/Users/madhavkrsn/Desktop/MachineLearning/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [80]:
y_pred = model.predict(X_test)
y_pred

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1])

In [81]:
from sklearn.metrics import accuracy_score, confusion_matrix , classification_report

accuracy_score(y_test,y_pred)

0.7921348314606742

In [82]:
confusion_matrix(y_test,y_pred)

array([[89, 20],
       [17, 52]])

In [83]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.84      0.82      0.83       109
           1       0.72      0.75      0.74        69

    accuracy                           0.79       178
   macro avg       0.78      0.79      0.78       178
weighted avg       0.79      0.79      0.79       178



In [84]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()



In [85]:
df

survived  pclass  sex        age  sibsp  parch     fare  embarked  alone
0           0       3    1  29.699118      1      0   7.2500         2  False
1           1       1    0  29.699118      1      0  71.2833         0  False
2           1       3    0  29.699118      0      0   7.9250         2   True
3           1       1    0  29.699118      1      0  53.1000         2  False
4           0       3    1  29.699118      0      0   8.0500         2   True
..        ...     ...  ...        ...    ...    ...      ...       ...    ...
886         0       2    1  29.699118      0      0  13.0000         2   True
887         1       1    0  29.699118      0      0  30.0000         2   True
888         0       3    0  29.699118      1      2  23.4500         2  False
889         1       1    1  29.699118      0      0  30.0000         0   True
890         0       3    1  29.699118      0      0   7.7500         1   True

[889 rows x 9 columns]

In [86]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

In [87]:
from sklearn.neighbors import KNeighborsClassifier
knn_model = KNeighborsClassifier(n_neighbors=5)



In [88]:
knn_model.fit(X_train_scaled,y_train)

KNeighborsClassifier()

In [89]:
y_pred_knn = knn_model.predict(X_test_scaled)

In [90]:
accuracy_score(y_test,y_pred_knn) #knn

0.7415730337078652

In [91]:
accuracy_score(y_test,y_pred)  #logistic regression

0.7921348314606742

In [92]:
confusion_matrix(y_pred_knn,y_test)

array([[85, 22],
       [24, 47]])

In [93]:
print(classification_report(y_pred_knn,y_test))

              precision    recall  f1-score   support

           0       0.78      0.79      0.79       107
           1       0.68      0.66      0.67        71

    accuracy                           0.74       178
   macro avg       0.73      0.73      0.73       178
weighted avg       0.74      0.74      0.74       178



NAIVE BAYE"S


In [94]:
from sklearn.naive_bayes import GaussianNB
model_naive = GaussianNB()
model_naive.fit(X_train,y_train)
y_pred_naive = model_naive.predict(X_test)


In [95]:
from sklearn.metrics import accuracy_score, confusion_matrix,classification_report
accuracy = accuracy_score(y_pred_naive,y_test)
print("Accuracy:", accuracy)

Accuracy: 0.7696629213483146


In [96]:
confusion_matrix(y_pred,y_test)

array([[89, 17],
       [20, 52]])

In [97]:
print(classification_report(y_pred_naive,y_test))

              precision    recall  f1-score   support

           0       0.76      0.85      0.80        98
           1       0.78      0.68      0.72        80

    accuracy                           0.77       178
   macro avg       0.77      0.76      0.76       178
weighted avg       0.77      0.77      0.77       178



DESCISION TREE

In [98]:
from sklearn.tree import DecisionTreeClassifier


In [99]:
model_Dt = DecisionTreeClassifier(
    criterion='gini',
    max_depth=5,
    random_state=42
)
model_Dt.fit(X_train,y_train)


DecisionTreeClassifier(max_depth=5, random_state=42)

In [100]:
y_pred_Dt = model_Dt.predict(X_test)


In [101]:
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.7921348314606742


In [102]:
print(confusion_matrix(y_test, y_pred))

[[89 20]
 [17 52]]


In [103]:
print(classification_report(y_test, y_pred))



              precision    recall  f1-score   support

           0       0.84      0.82      0.83       109
           1       0.72      0.75      0.74        69

    accuracy                           0.79       178
   macro avg       0.78      0.79      0.78       178
weighted avg       0.79      0.79      0.79       178



SVM :: Support Vector Machine

In [104]:
from sklearn.svm import SVC
model_svm = SVC(kernel='rbf')
model_svm.fit(X_train,y_train)
y_pred_svm = model_svm.predict(X_test)
y_pred_svm

array([0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [105]:
accuracy_score(y_pred,y_test)

0.7921348314606742

In [106]:
#CROSS VALIDATION
df

survived  pclass  sex        age  sibsp  parch     fare  embarked  alone
0           0       3    1  29.699118      1      0   7.2500         2  False
1           1       1    0  29.699118      1      0  71.2833         0  False
2           1       3    0  29.699118      0      0   7.9250         2   True
3           1       1    0  29.699118      1      0  53.1000         2  False
4           0       3    1  29.699118      0      0   8.0500         2   True
..        ...     ...  ...        ...    ...    ...      ...       ...    ...
886         0       2    1  29.699118      0      0  13.0000         2   True
887         1       1    0  29.699118      0      0  30.0000         2   True
888         0       3    0  29.699118      1      2  23.4500         2  False
889         1       1    1  29.699118      0      0  30.0000         0   True
890         0       3    1  29.699118      0      0   7.7500         1   True

[889 rows x 9 columns]

In [107]:
X = df.drop('survived',axis=1)
y = df['survived']
X = pd.get_dummies(X,drop_first=True) #drop first yani ek catergorical column hata do like male = 1 and female 0 aisa type 

# X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler

In [108]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled
X

pclass  sex        age  sibsp  parch     fare  embarked  alone
0         3    1  29.699118      1      0   7.2500         2  False
1         1    0  29.699118      1      0  71.2833         0  False
2         3    0  29.699118      0      0   7.9250         2   True
3         1    0  29.699118      1      0  53.1000         2  False
4         3    1  29.699118      0      0   8.0500         2   True
..      ...  ...        ...    ...    ...      ...       ...    ...
886       2    1  29.699118      0      0  13.0000         2   True
887       1    0  29.699118      0      0  30.0000         2   True
888       3    0  29.699118      1      2  23.4500         2  False
889       1    1  29.699118      0      0  30.0000         0   True
890       3    1  29.699118      0      0   7.7500         1   True

[889 rows x 8 columns]

scores = cross_val_score(model_svm,X_scaled,y,cv=5,scoring='accuracy')
print(scores)

In [110]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression

model = LinearRegression()

scores = cross_val_score(
    model,
    X_scaled,
    y,
    cv=5,
    scoring='neg_mean_squared_error'
)

print("MSE per fold:", -scores)
print("Mean MSE:", -scores.mean())


MSE per fold: [0.15908473 0.15822279 0.14777834 0.16075562 0.13119754]
Mean MSE: 0.15140780401669376


In [ ]:
model = SVC()
scores = cross_val_score(
    model,
    X_scaled,
    y,
    cv=5,
    scoring='accuracy'
)

print(scores)
print(scores.mean())

[0.79213483 0.81460674 0.80898876 0.80337079 0.82485876]


np.float64(0.8087919761315305)